---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:bullseye
          - debian:testing
          - debian:unstable
          - ubuntu:focal
          - ubuntu:hirsute
          - ubuntu:impish
          - ubuntu:latest
          - ubuntu:rolling
        yaml_package:
          - python3-ruamel.yaml
          - python3-yaml
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          apt-get update &&
          apt-get install --yes black isort pylint python3 python3-coverage
          python3-flake8 python3-jinja2 ${{ matrix.yaml_package }}
      - name: Run unit tests
        run: |
          python3 -m coverage run -m unittest discover -v
          python3 -m coverage xml
      - name: Install dependencies for Codecov
        run: apt-get install --yes curl git
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          functionalities: gcov

  # Debian buster needs pylint3 instead of pylint
  unittest-debian-buster:
    name: unittest debian:buster
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yaml_package:
          - python3-ruamel.yaml
          - python3-yaml
    container:
      image: debian:buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          apt-get update &&
          apt-get install --yes black isort pylint3 python3 python3-flake8
          python3-jinja2 ${{ matrix.yaml_package }}
      - name: Run unit tests
        run: python3 -m unittest discover -v
